# ['sift', 'rootsift', 'ssd']
detector_type: ssd
# path to TensorFlow Object Detection API frozen inference graph
inference_graph: /xavier_ssd/ssdnet/frozen_inference_graph.pb
# path to TensorFlow Object Detection API label map
label_map: /xavier_ssd/Core/models/research/object_detection/data/mscoco_label_map.pbtxt

# confidence level to report objects as detected
ssd_confidence: 0.7

# minimum number of points to consider an object as present in the scene
#sift_min_pts: 10

# path to the database used by the keypoint object detector
#sift_database_path: ~/.dodo_detector_ros/sift_database

# the frame or tf that all object tfs will be published in relation to, leave blank to publish wrt.
global_frame: map