map_type: costmap
origin_z: 0.0
z_resolution: 0.05 # The z resolution of the map in meters/cell.
z_voxels: 2  # The number of voxels to in each vertical column, the height of the grid is z resolution * z voxels.
#

obstacle_range: 5.5 # The default maximum distance from the robot at which an obstacle will be inserted into the cost map in meters.
raytrace_range: 5.0 # The default range in meters at which to raytrace out obstacles from the map using sensor data

#
publish_voxel_map: true
robot_base_frame: base_link


footprint: [[-0.25, -0.165], [-0.25, 0.165], [0.21, 0.165], [0.21, -0.165]]
footprint_padding: 0.01
inflation_radius: 0.15  # controls how far away the zero cost point is from the obstacle
cost_scaling_factor: 1
# slope of the cost decay curve with respect to distance from the object. lower makes robot stay further from obstacles

NavfnROS:
    allow_unknown: true

recovery_behaviors: [
    {name: conservative_clear, type: clear_costmap_recovery/ClearCostmapRecovery},
    {name: aggressive_clear, type: clear_costmap_recovery/ClearCostmapRecovery} # este limpia fuera de un radio de 4*circum_radius
]
